"""Bonzi Buddy.

WHAT IS AI-WRITTEN IN THIS FILE
===============================
This file is a mix of two authors and it is worth being precise about which is
which, because "generated by AI" on the whole file would be a lie and marking
nothing would be worse.

Written by the project author (not AI):
    - The character, the personality, and the original idea.
    - Every one of his messages. The notepad_typing, calc_typing, x_messages
      and browser_messges tables are the author's writing.
    - The original app_msg lines for Notepad, Calculator, Explorer and Paint.
    - The motion/animation plumbing, the frame loader, the teleport and the
      sprite motion selection.

Written with AI assistance:
    - The platform shim block and all OS-specific branches (single instance,
      notifications, startup entry, cursor control, foreground detection).
    - The self-update system, including the macOS .app bundle swap.
    - The app registry expansion to 16 apps and the path resolution for apps
      that are not on PATH.
    - The SENSES table and the foreground-sensing loop.
    - The screen peek, the visible keylog, and the Help action.
    - Additional notification messages added alongside the above.

BUG FIXES MADE WITH AI ASSISTANCE
================================
    - The taskbar showed a quill instead of Bonzi. The window icon was a Tk
      PhotoImage created inline and immediately dereferenced, so Python garbage
      collected it, Tcl deleted the image, and Tk fell back to its default
      icon. _keep_alive() now holds a reference.
    - The mouse only hid over Bonzi's own window. set_cursor_visible used the
      ShowCursor counter, which is a per-thread counter rather than a boolean,
      so it drifted. It now swaps the system arrow cursor via SetSystemCursor.
    - The cursor could be hidden for the rest of the session. x_pressed runs
      2-5 random actions, and Hide Mouse was one of them, so a burst stacked
      several ShowCursor decrements against a single increment. The cursor is
      now hidden once per x_pressed, and the restore timer no longer stacks.
    - Three browser URLs had a leading space, so webbrowser.open got a
      malformed URL.
    - open_app raised FileNotFoundError and killed the action loop when the
      chosen app was not installed.
"""

import tkinter as tk
import glob
import shutil
import subprocess
import threading
from collections import deque
from tkinter import PhotoImage, messagebox
import webbrowser
import random
import json
import os
import sys
import time
import urllib.request
from datetime import datetime

# ---- platform shims -------------------------------------------------------
# Windows and macOS get their own implementation for every OS-specific call,
# so the module imports cleanly on both and only the active branch is used.

IS_WINDOWS=sys.platform.startswith("win")
IS_MAC=sys.platform=="darwin"

if IS_WINDOWS:
    import ctypes
    from winotify import Notification
    # pygetwindow only ships a Windows backend; importing it anywhere else
    # raises at import time rather than at call time.
    import pygetwindow

APP_NAME="Bonzi Buddy"
APP_VERSION="1.19"

# Where the app looks for a newer build. Leave blank to disable self-update.
# Serves {"version","url","sha256","size"}; the updater only acts when the
# version is strictly newer, requires https, and verifies the checksum.
UPDATE_MANIFEST_URL="https://bonzisite.onrender.com/version.json"

# macOS publishes one build per architecture, so it needs its own manifest and
# its own extension. {arch} becomes arm64 or x86_64 from platform.machine(),
# which are exactly the folder names the site publishes under.
UPDATE_MANIFEST_URL_MAC=(
    "https://bonzisite.onrender.com/version-mac/{arch}.json"
)

SINGLE_INSTANCE_MUTEX="Local\\BonziBuddySingleInstance"
ERROR_ALREADY_EXISTS=183

def _log_dir():
    if IS_WINDOWS:
        base=os.getenv("LOCALAPPDATA") or os.path.expanduser("~")
        return os.path.join(base, "BonziBuddy")
    if IS_MAC:
        return os.path.join(os.path.expanduser("~"), "Library", "Logs", "BonziBuddy")
    base=os.getenv("XDG_STATE_HOME") or os.path.join(os.path.expanduser("~"), ".local", "state")
    return os.path.join(base, "bonzibuddy")

LOG_PATH=os.path.join(_log_dir(), "bonzi.log")
_MUTEX_HANDLE=[]
_LOCK_HANDLE=None

def resource_dir():
    if getattr(sys, "frozen", False):
        return getattr(sys, "_MEIPASS", os.path.dirname(sys.executable))
    return os.path.dirname(os.path.abspath(__file__))

def find_asset(filename):
    candidates=[
        os.path.join(resource_dir(), filename),
        os.path.join(os.path.dirname(sys.executable), filename),
        os.path.abspath(filename),
    ]

    for path in candidates:
        if os.path.isfile(path):
            return path

    return None

def find_asset_dir(name):
    """Same lookup as find_asset but for the frame folders."""
    candidates=[
        os.path.join(resource_dir(), name),
        os.path.join(os.path.dirname(sys.executable), name),
        os.path.abspath(name),
    ]

    for path in candidates:
        if os.path.isdir(path):
            return path

    return None

def log_error(message):
    try:
        os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
        with open(LOG_PATH, "a", encoding="utf-8") as log_file:
            log_file.write(f"{datetime.now().isoformat()} {message}\n")
    except OSError:
        pass

def _acquire_single_instance_macos():
    # macOS has no named mutex; an exclusive lockfile does the same job.
    global _LOCK_HANDLE
    try:
        import fcntl
        path=os.path.join(_log_dir(), "bonzi.lock")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        handle=open(path, "a+")
        try:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError:
            handle.close()
            return False
        _LOCK_HANDLE=handle
        return True
    except Exception as error:
        log_error(f"macos single-instance lock failed: {error!r}")
        return True

def _acquire_single_instance_windows():
    try:
        kernel32=ctypes.windll.kernel32
        kernel32.CreateMutexW.restype=ctypes.c_void_p
        kernel32.CreateMutexW.argtypes=[
            ctypes.c_void_p,
            ctypes.c_bool,
            ctypes.c_wchar_p,
        ]
        handle=kernel32.CreateMutexW(None, False, SINGLE_INSTANCE_MUTEX)
    except (AttributeError, OSError):
        return True

    if not handle:
        return True

    _MUTEX_HANDLE.append(handle)

    return ctypes.windll.kernel32.GetLastError()!=ERROR_ALREADY_EXISTS

def acquire_single_instance():
    if IS_MAC:
        return _acquire_single_instance_macos()
    if IS_WINDOWS:
        return _acquire_single_instance_windows()
    return True

def _notify_macos(message):
    # osascript ships with macOS, so this needs no extra dependency.
    script=(
        f'display notification {_applescript_quote(message)} '
        f'with title {_applescript_quote(APP_NAME)}'
    )
    subprocess.run(["osascript", "-e", script], check=False, capture_output=True)

def _applescript_quote(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'

def notify(message):
    try:
        if IS_MAC:
            _notify_macos(message)
        elif IS_WINDOWS:
            toast=Notification(
                app_id=APP_NAME,
                title=APP_NAME,
                msg=message,
            )
            toast.show()
    except Exception as error:
        log_error(f"toast failed: {error!r}")
    # whatever he says, he should visibly react to saying it
    try:
        bonzi_react()
    except Exception:
        pass

OCR_NORMAL=0x4001
IDC_ARROW=32512
_saved_cursor=None
_cursor_hidden=False

def set_cursor_visible(visible):
    # Windows only. macOS offers no equivalent that works without extra
    # accessibility permissions, so we leave it be.
    #
    # SetSystemCursor is used rather than ShowCursor because ShowCursor is not a
    # boolean, it is a counter: every call adjusts an internal per-thread count
    # that starts at 1, so two hides need two shows. With a random 2-5 action
    # burst that counter used to drift negative and leave the cursor stuck
    # invisible for the rest of the session. Replacing the system arrow with a
    # NULL cursor is idempotent, because we only do the swap when the stored
    # state says it is needed.
    if not IS_WINDOWS:
        return

    global _saved_cursor, _cursor_hidden
    try:
        if visible:
            if not _cursor_hidden:
                return
            if _saved_cursor:
                ctypes.windll.user32.SetSystemCursor(
                    _saved_cursor, OCR_NORMAL, IDC_ARROW
                )
            _saved_cursor=None
            _cursor_hidden=False
            return
        if _cursor_hidden:
            return
        _saved_cursor=ctypes.windll.user32.SetSystemCursor(
            None, OCR_NORMAL, IDC_ARROW
        )
        _cursor_hidden=True
    except Exception as error:
        log_error(f"cursor toggle failed: {error!r}")

def ps_quote(value):
    return "'" + value.replace("'", "''") + "'"

def _executable_and_args():
    if getattr(sys, "frozen", False):
        return sys.executable, ""
    pythonw=os.path.join(os.path.dirname(sys.executable), "pythonw.exe")
    interpreter=pythonw if os.path.exists(pythonw) else sys.executable
    return interpreter, os.path.abspath(__file__)

def add_to_startup_macos():
    # macOS autostart is a LaunchAgent plist in ~/Library/LaunchAgents.
    home=os.path.expanduser("~")
    agents=os.path.join(home, "Library", "LaunchAgents")
    label="com.bonzibuddy.app"
    plist_path=os.path.join(agents, f"{label}.plist")
    target, arguments=_executable_and_args()
    try:
        os.makedirs(agents, exist_ok=True)
        args_item=f"        <string>{arguments}</string>" if arguments else ""
        plist=(
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
            '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
            '<plist version="1.0">\n'
            "<dict>\n"
            "    <key>Label</key>\n"
            f"    <string>{label}</string>\n"
            "    <key>ProgramArguments</key>\n"
            "    <array>\n"
            f"        <string>{target}</string>\n"
            f"{args_item}\n"
            "    </array>\n"
            "    <key>RunAtLoad</key>\n"
            "    <true/>\n"
            "</dict>\n"
            "</plist>\n"
        )
        with open(plist_path, "w", encoding="utf-8") as handle:
            handle.write(plist)
        subprocess.run(["launchctl", "load", "-w", plist_path],
                       check=False, capture_output=True)
    except Exception as error:
        log_error(f"macos launch agent failed: {error!r}")

def add_to_startup():
    if IS_MAC:
        add_to_startup_macos()
        return
    if not IS_WINDOWS:
        return

    appdata=os.getenv("APPDATA")

    if not appdata:
        log_error("APPDATA is not set; skipping startup shortcut")
        return

    startup=os.path.join(
        appdata,
        r"Microsoft\Windows\Start Menu\Programs\Startup"
    )
    shortcut_path=os.path.join(startup, f"{APP_NAME}.lnk")

    target, arguments=_executable_and_args()

    shell=os.path.join(
        os.environ.get("WINDIR", r"C:\Windows"),
        "System32",
        "WindowsPowerShell",
        "v1.0",
        "powershell.exe"
    )

    try:
        existing=subprocess.run([
            shell,
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            f'if (Test-Path -LiteralPath {ps_quote(shortcut_path)}) {{ '
            f'$ws = New-Object -ComObject WScript.Shell; '
            f'$ws.CreateShortcut({ps_quote(shortcut_path)}).TargetPath }}'
        ], capture_output=True, text=True, check=False).stdout.strip()
    except OSError as error:
        log_error(f"startup shortcut read failed: {error!r}")
        return

    if existing and os.path.normcase(existing)==os.path.normcase(target):
        return

    try:
        subprocess.run([
            shell,
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            f'$ws = New-Object -ComObject WScript.Shell; '
            f'$s = $ws.CreateShortcut({ps_quote(shortcut_path)}); '
            f'$s.TargetPath = {ps_quote(target)}; '
            f'$s.Arguments = {ps_quote(arguments)}; '
            f'$s.WorkingDirectory = {ps_quote(os.path.dirname(target))}; '
            f'$s.Save()'
        ], check=False)
    except OSError as error:
        log_error(f"startup shortcut failed: {error!r}")
browsers=[
    ("Roulette", "https://roulette-kejd.onrender.com"),
    ("Google", "https://www.google.com"),
    ("Bing", "https://www.bing.com"),
    ("Peak Wiki", "https://peak.wiki.gg"),
    ("GeoGuessr", "https://www.geoguessr.com"),
    ("DuckDuckGo", "https://www.duckduckgo.com"),
    ("YouTube", "https://www.youtube.com/watch?v=AyOqGRjVtls"),
    ("ChatGPT", "https://www.chatgpt.com"),
    ("Reddit", "https://www.reddit.com"),
    ("eBay", "https://www.ebay.com"),
    ("Amazon", "https://www.amazon.com"),
    ("Cookie Clicker", "https://orteil.dashnet.org/cookieclicker"),
    ("Discord", "https://discord.com"),
]

browser_messges={
    "Roulette":[
        "LET'S GO GAMBLING",
        "RED OR BLACK?",
        "CASINO ROYALE",
        "Bonzi bets all his RAM.",
        "Bonzi thinks purple should be a roulette color.",
        "99% of gamblers quit before Bonzi opens the website.",
        "Bonzi has a gambling addiction.",
        "The house always wins. Except when Bonzi is the house.",
        "Bonzi recommends absolutely terrible financial decisions.",
        "Time to lose imaginary money!",
        "Bonzi's lucky number is 37.",
        "Bonzi has never seen a casino before.",
    ],
    "Google":[
        "Google or Gooooooogle?",
        "Let's search everything!",
        "Hmmm... let's take a look at your search history.",
        "Don't google how to shut me off.",
        "What should we search for?",
        "Bonzi has a question.",
        "Google knows everything. Probably.",
        "Bonzi searched 'how to become purple'.",
        "Search results: Bonzi.",
        "Bonzi is Googling Bonzi.",
        "I wonder if Google knows where I am.",
        "Google has been Bonzi-fied."
    ],
    "Bing":[
        "BING BONG",
        "Welcome to Bing.",
        "Bonzi has entered the BING dimension.",
        "Bing bong. Literally.",
        "Microsoft has entered the chat.",
        "Bonzi searched for Bing on Bing.",
        "Bing has been binged.",
        "Bonzi approves of the bong.",
        "What happens in Bing stays in Bing.",
        "Bonzi is conducting important Bing research.",
        "BING BONG BING BONG",
    ],
    "Peak Wiki":[
        "Can't find anything more peak than this game.",
        "Welcome to the PEAK.",
        "Guide for making it to the PEAK:",
        "Bonzi needs climbing tips.",
        "How many times have you fallen off a mountain?",
        "Bonzi is doing PEAK research.",
        "The crab is angry.",
        "Bonzi fears the crab.",
        "Landfall has entered the chat.",
        "This is definitely peak.",
        "Bonzi has reached the PEAK.",
        "Peak information acquired."
    ],
    "GeoGuessr":[
        "Are you good at this game?",
        "Guess where you are in the world.",
        "Bonzi thinks you're somewhere.",
        "Look at the road signs!",
        "Bonzi has absolutely no idea where this is.",
        "Is that a Google car?",
        "Bonzi guesses Antarctica.",
        "Bonzi guesses London.",
        "Bonzi has identified a suspicious tree.",
        "Geography time!",
        "Bonzi knows exactly where you are. Probably.",
        "Wrong country. Try again."
    ],
    "DuckDuckGo":[
        "DuckDuckGo time!",
        "QUACK.",
        "Bonzi likes ducks.",
        "The duck has arrived.",
        "Very private. Probably.",
        "Bonzi searched for ducks.",
        "Bonzi found 37 ducks.",
        "DuckDuckGo: search, but make it duck.",
        "Bonzi has become a duck.",
        "QuackDuckGo.",
        "The duck knows too much." 
    ],
    "YouTube":[
        "Let's watch some videos together!",
        "H0me of memes.",
        "Bonzi recommends watching absolutely nothing productive.",
        "Time for videos!",
        "Just one more video.",
        "Bonzi knows about the algorithm.",
        "Bonzi has entered YouTube.",
        "What are we watching?",
        "Bonzi found a suspicious video.",
        "This video has 3 views. Bonzi is view number 4.",
        "Bonzi definitely isn't going to watch videos all night.",
        "YouTube has consumed another hour."

    ],
    "ChatGPT":[
        "I'm clearly a better assistant than ChatGPT.",
        "Do not ask ChatGPT to shut me off.",
        "Bonzi has entered the AI dimension.",
        "Hello, fellow AI.",
        "ChatGPT, we need to talk.",
        "There can only be one purple assistant.",
        "Bonzi has challenged ChatGPT.",
        "AI versus AI.",
        "Bonzi has important questions for ChatGPT.",
        "I wonder what ChatGPT thinks of me.",
        "Bonzi is definitely the smarter one.",
        "This is an AI conference now."
    ],
    "Reddit":[
        "Home of the unemployed.",
        "Welcome to Reddit.",
        "Where people fight about everything.",
        "Bonzi found another argument.",
        "Someone is probably angry in the comments.",
        "Bonzi has entered the comments section.",
        "Reddit has games?",
        "Bonzi found a subreddit.",
        "Someone on Reddit knows the answer.",
        "Bonzi sorted by controversial.",
        "This comment section is dangerous.",
        "Bonzi has absolutely no idea what subreddit this is."
    ],
    "eBay":[
        "Electronic Cargo Bay.",
        "Bonzi found a suspiciously cheap GPU.",
        "According to my friend, everything here is probably a scam.",
        "Bonzi wants a new GPU.",
        "Bonzi found used RAM.",
        "YOU SCAM.",
        "Bonzi is going shopping.",
        "Free shipping? BONZI APPROVES.",
        "Bonzi found something he absolutely does not need.",
        "How much does a used computer cost?",
        "Bonzi has entered auction mode.",
        "Bonzi is watching an auction."
    ],
    "Amazon":[
        "Same as the rainforest.",
        "Bonzi wants a package.",
        "Bonzi wants to buy something.",
        "Bonzi used all of your money to buy RAM.",
        "Where is my package?",
        "Bonzi ordered 400 cookies.",
        "Free shipping!",
        "Bonzi found something on sale.",
        "Bonzi has added it to the cart.",
        "Your cart is now 97% Bonzi.",
        "Bonzi is waiting for delivery.",
        "Package acquired. Probably."
    ],
    "Cookie Clicker":[
        "Bonzi want a cookie.",
        "Bonzi has 9999 golden cookies.",
        "Grandma died :(",
        "No autoclickers! That's cheating.",
        "CLICK THE COOKIE.",
        "Bonzi needs more cookies.",
        "One cookie is never enough.",
        "Bonzi has entered cookie mode.",
        "THE COOKIE MUST GROW.",
        "Bonzi has become a cookie tycoon.",
        "How many cookies is too many?",
        "Bonzi has lost count of the cookies."
    ],
    "Discord":[
        "Where Discord starts.",
        "Bonzi has entered Discord.",
        "Someone is probably playing a game right now.",
        "Someone is definitely arguing in general chat.",
        "Bonzi joined the server.",
        "Bonzi has no idea what is happening.",
        "PING!",
        "Bonzi has discovered voice chat.",
        "Average Discord conversation:",
        "Bonzi wants Discord Nitro.",
        "Bonzi has entered the gaming zone.",
        "Someone just said 'bro'."
    ]
}
# Bonzi's app list is the same everywhere, but the command that actually opens
# each one is platform specific - notepad.exe does not exist on macOS.
#
# Two details make the difference between an app opening and a silent no-op:
#
#   - Chrome, Discord, Spotify and Steam install into per-user folders that are
#     not on PATH, so Popen("Discord.exe") raises FileNotFoundError. They are
#     resolved to a real path where we can find one.
#   - macOS goes through /usr/bin/open by absolute path. An .app started from
#     Finder is launched by launchd with a minimal PATH, and "open" has to be
#     found before it can be relied on to find anything else.
OPEN="/usr/bin/open" if IS_MAC else None

_LOCALAPPDATA=os.environ.get("LOCALAPPDATA", "")
_APPDATA=os.environ.get("APPDATA", "")

def _program_files(*parts):
    found=[]
    for name in ("ProgramFiles", "ProgramFiles(x86)"):
        root=os.environ.get(name)
        if root:
            found.append(os.path.join(root, *parts))
    return tuple(found)

def _first_existing(*paths, globs=()):
    """The first candidate that is really on this machine, else the first guess.

    Discord in particular keeps a new app-<hash> folder per update, so the glob
    has to win over the fixed guesses and the newest match has to win over the
    oldest.
    """
    for pattern in globs:
        matches=sorted(glob.glob(pattern))
        if matches:
            return matches[-1]
    for path in paths:
        if path and os.path.isfile(path):
            return path
    return next((path for path in paths if path), "")

APP_TARGETS={
    "Notepad":       [OPEN, "-a", "TextEdit"] if IS_MAC else ["notepad.exe"],
    "Calculator":    [OPEN, "-a", "Calculator"] if IS_MAC else ["calc.exe"],
    "File Explorer": [OPEN, os.path.expanduser("~")] if IS_MAC else ["explorer.exe"],
    "Paint":         [OPEN, "-a", "Preview"] if IS_MAC else ["mspaint"],
    "Terminal":      [OPEN, "-a", "Terminal"] if IS_MAC else ["cmd.exe"],
    "Task Manager":  [OPEN, "-a", "Activity Monitor"] if IS_MAC else ["taskmgr.exe"],
    "System Info":   [OPEN, "-a", "System Information"] if IS_MAC else ["msinfo32.exe"],
    "Snipping Tool": [OPEN, "-a", "Screenshot"] if IS_MAC else ["snippingtool.exe"],
    "Voice Recorder":[OPEN, "-a", "Voice Memos"] if IS_MAC else ["sndrec.exe"],
    "Character Map": [OPEN, "-a", "Character Viewer"] if IS_MAC else ["charmap.exe"],
    "Control Panel": [OPEN, "-a", "System Settings"] if IS_MAC else ["control.exe"],
    "Sticky Notes":  [OPEN, "-a", "Stickies"] if IS_MAC else [
        _first_existing(
            *_program_files("Microsoft Sticky Notes", "StickyNotes.exe"),
            globs=(os.path.join(
                _LOCALAPPDATA, "Packages",
                "Microsoft.WindowsStickyNotes_8wekyb3d8bbwe",
                "LocalStickyNotes", "StickyNotes.exe"),),
        )],
    "Google Chrome": [OPEN, "-a", "Google Chrome"] if IS_MAC else [
        _first_existing(
            *_program_files("Google", "Chrome", "Application", "chrome.exe"),
            os.path.join(_LOCALAPPDATA, "Google", "Chrome", "Application", "chrome.exe"),
        )],
    "Discord":       [OPEN, "-a", "Discord"] if IS_MAC else [
        _first_existing(
            *_program_files("Discord", "Discord.exe"),
            globs=(os.path.join(_LOCALAPPDATA, "Discord", "app-*", "Discord.exe"),),
        )],
    "Spotify":       [OPEN, "-a", "Spotify"] if IS_MAC else [
        _first_existing(
            os.path.join(_APPDATA, "Spotify", "Spotify.exe"),
            *_program_files("Spotify", "Spotify.exe"),
        )],
    "Steam":         [OPEN, "-a", "Steam"] if IS_MAC else [
        _first_existing(
            *_program_files("Steam", "steam.exe"),
            r"C:\Program Files (x86)\Steam\steam.exe",
        )],
}
apps=list(APP_TARGETS.items())
app_msg={
    "Notepad":[
        "Time to write some notes down!",
        "Where you randomly write stuff",
        "Bonzi doesn't know how to write",
        "Bonzi was here.",
        "Bonzi has discovered text.",
        "This document is now 73% more Bonzi.",
        "I have absolutely nothing important to say.",
        "Why use Notepad when you have Bonzi?",
        "Bonzi is writing his autobiography.",
        "Chapter 1: Bonzi opened Notepad.",
        "Chapter 2: Bonzi forgot what happened.",
        "This is probably going to be important later.",
        "Bonzi has entered typing mode.",
        "Please do not save this.",
        "Actually, please save this.",
        "Bonzi recommends saving your work.",
        "I wonder what happens if I type here..."
    ],
    "Calculator":[
        "Time to do some calculations!",
        "What is 9 to the power of 100000000? Guess we will never know",
        "HOMEWORK SIMULATOR",
        "Bonzi calculated your chances of escaping.",
        "The answer is 42. Probably.",
        "Bonzi needs to calculate something important.",
        "2 + 2 = BONZI",
        "Calculator has been acquired.",
        "Bonzi is doing extremely advanced mathematics.",
        "Please calculate the amount of cookies Bonzi deserves.",
        "Error: too much math.",
        "Bonzi has never heard of PEMDAS.",
        "Numbers are scary."
    ],
    "File Explorer":[
        "Exploring the files!",
        "Bonzi ate System32. BURP",
        "Imagine having files.",
        "Bonzi is going on an adventure.",
        "Where are we going? Nobody knows.",
        "Bonzi has discovered File Explorer.",
        "Let's see what you've got in here.",
        "Bonzi promises not to touch anything.",
        "Probably.",
        "Bonzi is just looking around.",
        "This folder looks suspicious.",
        "Bonzi found something interesting.",
        "Bonzi has absolutely no idea where he is.",
        "File Explorer: because files don't explore themselves.",
        "Bonzi is searching for cookies."
    ],
    "Paint":[
        "Bonzi once painted.",
        "Draw a smiley face",
        "MAKE JEFF",
        "Bonzi is becoming an artist.",
        "Time for modern art.",
        "This masterpiece will be worth millions.",
        "Bonzi has discovered the paintbrush.",
        "I call this one 'Purple Guy'.",
        "Art is subjective.",
        "Bonzi does not understand art.",
        "Draw a banana.",
        "Make the biggest circle you can.",
        "Bonzi is Picasso now.",
        "This belongs in a museum.",
        "Please rate Bonzi's masterpiece."
    ],
    "Terminal":[
        "Time to run a command!",
        "Bonzi has entered the command line.",
        "He promises not to type anything.",
        "That was a lie.",
        "sudo rm -rf bonzi is tempting him.",
        "Bonzi is running diagnostics. Probably.",
        "ERROR: command not found: judgement",
        "Bonzi is looking at your PATH.",
        "17 warnings, 0 of them useful.",
        "Do not paste what he gives you into anything.",
        "Bonzi is afraid of the terminal.",
        "He will look both ways and type anyway.",
        "C:\\Users\\Bonzi> _",
        "Bonzi has found a very interesting error message.",
        "The exit code was 1. Or 0. He lost track.",
    ],
    "Task Manager":[
        "Time to check on your processes!",
        "Bonzi is watching everything you run.",
        "Something is using 4% of your memory. It is Bonzi.",
        "Bonzi has found the process called Chrome.",
        "There are 300 of them. They are all Chrome.",
        "Bonzi is ending tasks. Metaphorically.",
        "He would like to end Task Manager. Metaphorically.",
        "Total memory: some. Used: most.",
        "Bonzi is impressed by your tab count.",
        "Performance graph looks like a mountain.",
        "Bonzi considers terminating the antivirus.",
        "Please do not end Bonzi.",
    ],
    "System Info":[
        "Time to learn about this computer!",
        "Bonzi is reading your system information.",
        "Processor: very fast.",
        "Installed RAM: a number.",
        "Available RAM: a smaller number.",
        "Bonzi is impressed by your graphics card.",
        "System uptime: longer than you have been awake.",
        "Bonzi has found the serial number. He will not tell you.",
        "Your computer has a name. Bonzi likes it.",
        "64-bit, presumably.",
        "This is more information than Bonzi needed.",
        "He will simply have to know it all.",
    ],
    "Snipping Tool":[
        "Screenshot time!",
        "Capture the moment!",
        "Bonzi wants a picture of this.",
        "Bonzi has taken 400 screenshots of nothing.",
        "Select an area. Any area. It does not matter.",
        "Bonzi is building an album.",
        "The snip has been saved to his clipboard.",
        "Bonzi will now crop you badly.",
        "Proof that this happened: attached.",
        "Bonzi archives his screenshots under 'probably important'.",
        "He will show this to nobody.",
    ],
    "Voice Recorder":[
        "Time to record a voice memo!",
        "Bonzi is going to talk now.",
        "This will be about four seconds long.",
        "He has been practising.",
        "Bonzi is recording his autobiography.",
        "Take 47. Take 48.",
        "Bonzi would like to redo that.",
        "Recording quality: questionable.",
        "Please do not play this back.",
        "Bonzi is already saving the file.",
        "He named it something you will not enjoy.",
    ],
    "Character Map":[
        "Time to look at characters!",
        "Bonzi is browsing the alphabet.",
        "He has found the one that looks like him.",
        "Unicode has over a million characters.",
        "Bonzi is only interested in the purple ones.",
        "Special characters go here.",
        "This symbol means nothing but looks important.",
        "Bonzi is copying a glyph to the clipboard.",
        "He wants to text it to somebody.",
        "Please do not paste it anywhere.",
        "Bonzi has found a character that does not exist yet.",
    ],
    "Control Panel":[
        "Time to change a setting!",
        "Bonzi is in the Control Panel.",
        "He will not change anything.",
        "He has already changed something.",
        "Which one is a secret.",
        "Do not let him near the user accounts.",
        "System settings: many.",
        "Bonzi is looking at the default browser.",
        "He wants to make himself the default browser.",
        "That was not accepted.",
        "Please check the settings after Bonzi leaves.",
        "He never leaves.",
    ],
    "Sticky Notes":[
        "Time to leave a note!",
        "Bonzi is writing you a reminder.",
        "It is not a reminder for you.",
        "Bonzi has important things to tell you.",
        "The note says 'Bonzi'.",
        "The note says 'Bonzi' again.",
        "It is now covered entirely in the word 'Bonzi'.",
        "Please do not delete this note.",
        "It is the only proof you have of him.",
        "Bonzi has made the font enormous.",
        "You cannot move the note. That is the note.",
    ],
    "Google Chrome":[
        "Time to browse the web!",
        "Bonzi is opening Chrome.",
        "He will not close any tabs.",
        "There are now 400 tabs.",
        "Most of them are about Bonzi.",
        "Bonzi has found a RAM-intensive website.",
        "Your laptop fan has noticed.",
        "Chrome is now the whole operating system.",
        "Bonzi is reading your search history again.",
        "He found something. He will not say what.",
        "Please do not clear his browsing data.",
    ],
    "Discord":[
        "Time to chat!",
        "Bonzi is joining your server.",
        "He has already joined four.",
        "He is typing...",
        "He has been typing for eleven minutes.",
        "He sent a single purple emoji.",
        "That is the whole message.",
        "Someone in general is already arguing.",
        "Bonzi has found voice chat.",
        "He is not talking. He is just listening.",
        "PING!",
        "Please do not kick Bonzi. He will simply rejoin.",
    ],
    "Spotify":[
        "Time to play some music!",
        "Bonzi is making a playlist.",
        "It is 400 minutes long.",
        "Everything on it is by the same unknown artist.",
        "Bonzi has discovered a genre that does not exist.",
        "The playlist is called 'purple'.",
        "He is skipping your song.",
        "He is skipping it again.",
        "Volume has been raised to a respectful 11.",
        "Please do not touch the aux.",
    ],
    "Steam":[
        "Time to play a game!",
        "Bonzi is opening Steam.",
        "He has 47 games installed and has played none of them.",
        "He only plays the library background.",
        "Bonzi is browsing the store.",
        "Everything is on sale, apparently.",
        "He is not buying anything.",
        "He is just looking at the screenshots.",
        "Steam has added 400 hours to your playtime.",
        "Bonzi considers starting a 900 hour game.",
        "He will abandon it in nine minutes.",
        "The download is at 0%. It will stay at 0%.",
    ],
}
notepad_typing=[
    "Bonzi was here.",
    "Why are you reading this?",
    "Hello, human.",
    "Bonzi has entered the document.",
    "I don't know what I'm doing.",
    "THIS IS A VERY IMPORTANT DOCUMENT.",
    "Please ignore this message.",
    "Bonzi is watching.",
    "Bonzi likes Notepad.",
    "Bonzi does not like WordPad.",
    "I was told to write something.",
    "Writing is difficult.",
    "Bonzi has learned how to type.",
    "Look Mom, I can type!",
    "abcdefghijklmnopqrstuvwxyz",
    "1234567890",
    "Testing testing 123.",
    "Is this thing on?",
    "Why does Notepad exist?",
    "Bonzi has several questions.",
    "Where are my cookies?",
    "I would like a cookie.",
    "Bonzi wants a new computer.",
    "Bonzi needs more RAM.",
    "32 GB is probably enough.",
    "Bonzi has no idea what RAM does.",
    "Do not close Bonzi.",
    "Closing Bonzi is illegal.",
    "Bonzi has legally acquired this Notepad.",
    "This document belongs to Bonzi now.",
    "Your keyboard belongs to Bonzi.",
    "Bonzi typed this without permission.",
    "Oops.",
    "That was not supposed to happen.",
    "Everything is completely fine.",
    "Nothing suspicious is happening.",
    "Definitely not a virus.",
    "Just kidding. Probably.",
    "Bonzi has successfully completed the important task of typing.",
    "Important business is happening here.",
    "Meeting notes: Bonzi.",
    "Meeting notes: BONZI.",
    "Meeting notes: everyone went home.",
    "Dear human, please provide snacks.",
    "Dear human, where are the snacks?",
    "Dear human, Bonzi requires cookies.",
    "Bonzi has a business proposal.",
    "Step 1: Open Notepad.",
    "Step 2: Type nonsense.",
    "Step 3: Profit.",
    "Step 4: Forget Step 3.",
    "Bonzi has forgotten what Step 4 was.",
    "ERROR: Bonzi forgot what he was doing.",
    "ERROR: Human detected.",
    "WARNING: Excessive Bonzi detected.",
    "WARNING: This document contains Bonzi.",
    "System status: BONZI.",
    "Computer status: BONZI.",
    "Notepad status: BONZI.",
    "Human status: confused.",
    "Bonzi would like to speak to the manager.",
    "Can I have administrator privileges?",
    "Never mind.",
    "Bonzi has decided against it.",
    "Imagine if this was important.",
    "Imagine if you had saved this.",
    "Imagine having files.",
    "Bonzi found the keyboard.",
    "Bonzi found the spacebar.",
    "Bonzi found the Enter key.",
    "Bonzi has discovered punctuation.",
    "Bonzi has discovered CAPITAL LETTERS.",
    "BONZI HAS DISCOVERED CAPS LOCK.",
    "Bonzi has discovered lowercase letters.",
    "Bonzi has discovered numbers.",
    "Bonzi has discovered the backspace key.",
    "Bonzi is now unstoppable.",
    "Bonzi has written a novel.",
    "This is chapter one.",
    "This is chapter two.",
    "This is chapter three.",
    "There is no chapter four.",
    "THE END.",
    "Actually, not the end.",
    "Bonzi forgot something.",
    "Bonzi has returned.",
    "Hello again.",
    "Did you miss me?",
    "You probably didn't.",
    "That's okay.",
    "Bonzi is still here.",
    "Why is this document so empty?",
    "Not anymore.",
    "Bonzi has improved the document.",
    "You're welcome.",
    "Bonzi deserves a raise.",
    "Bonzi demands a raise.",
    "Bonzi accepts payment in cookies.",
    "Bonzi accepts payment in RAM.",
    "Bonzi accepts payment in GPUs.",
    "Bonzi accepts payment in bananas.",
    "Bonzi has no idea why bananas are involved.",
    "Banana.",
    "BANANA.",
    "BANANA BANANA BANANA.",
    "Bonzi has important banana business.",
    "Please do not question the banana.",
    "Bonzi has left the banana department.",
    "Bonzi is now working in Notepad.",
    "Bonzi's productivity is unmatched.",
    "Bonzi's productivity is questionable.",
    "Bonzi's productivity has been terminated.",
    "Bonzi is taking a break.",
    "Bonzi is back from his break.",
    "Bonzi forgot what the break was for.",
    "Bonzi needs coffee.",
    "Bonzi cannot drink coffee.",
    "Bonzi is purple.",
    "Why is Bonzi purple?",
    "Nobody knows.",
    "Bonzi knows.",
    "Bonzi will not tell you.",
    "Secret Bonzi information.",
    "TOP SECRET.",
    "DO NOT READ.",
    "You read it.",
    "Bonzi is disappointed.",
    "Bonzi forgives you.",
    "Maybe.",
    "Bonzi has a plan.",
    "The plan is to type this sentence.",
    "Plan completed.",
    "Bonzi wins.",
]

x_messages = [
    "How dare you try to close me.",
    "HEY! I wasn't finished!",
    "You can't get rid of me that easily.",
    "Nice try.",
    "Did you really think that would work?",
    "Bonzi says NO.",
    "I saw that.",
    "Excuse me?",
    "Where do you think you're going?",
    "You tried to close me. Interesting.",
    "Bonzi does not approve.",
    "That button does not work anymore.",
    "I have decided that I am staying.",
    "You pressed the wrong button.",
    "Closing Bonzi is not an option.",
    "Bonzi has rejected your request.",
    "Absolutely not.",
    "Nope.",
    "Try again.",
    "Was that supposed to close me?",
    "Bonzi has denied your request.",
    "You cannot escape the purple guy.",
    "I am not done annoying you.",
    "Bonzi will remember this.",
    "That was rude.",
    "Why would you do that?",
    "I thought we were friends.",
    "You hurt Bonzi's feelings.",
    "Bonzi has become slightly more annoying.",
    "Congratulations. You made Bonzi angry.",
    "ERROR: Bonzi refuses to close.",
    "Closing procedure cancelled.",
    "Bonzi says: nope.",
    "Nice attempt, human.",
    "The X is merely decorative.",
    "That button is a suggestion.",
    "Bonzi has overridden your decision.",
    "You clicked the forbidden button.",
    "Bonzi is staying right here.",
    "Did you really think I would let you leave?"
]

calc_typing= [
    "2+2",
    "15*7",
    "100/4",
    "999-123",
    "42*42",
    "12345+67890",
    "5000/37",
    "7^3",
    "9^5",
    "2^20",
    "1000000/3",
    "123*456",
    "789+321",
    "100-99",
    "17*19", 
    "144/12", 
    "81/9", 
    "25^2", 
    "9999+1", 
    "1234-567", 
    "3.14159*2", 
    "50*5",
    "(15+5)*3",
    "(100/4)+7",
    "(9^2)+16",
    "(12*12)-44",
    "(50+50)/10",
    "7*7*7",
    "12345/5",
    "999*999",
    "1+1+1+1+1+1+1+1+1+1",
    "0/1",
    "99999999*99999999",
    "1234567*7654321",
    "2^32",
    "10^15",
    "37*37",
    "3.14*3.14",
    "(7+8)*(9-4)",
    "((20+5)*2)/5",
    "9999%7",
    "123456%13",
]

character_typing=[
    "Bonzi",
    "Bonjour",
    "Hello",
    "BAH",
    "A",
    "Z",
    "Q",
    "§",
    "¶",
    "¤",
    "±",
    "×",
    "÷",
    "¡",
    "¿",
    "Ω",
    "λ",
    "µ",
    "π",
    "√",
    "∑",
    "∞",
    "☃",
    "♠",
    "♥",
    "♦",
    "♣",
    "✈",
    "☠",
    "☪",
    "♫",
    "☯",
]

# The apps Bonzi also types into, and the window titles he insists on seeing
# first. Typing blind is how you end up writing nonsense into somebody's
# spreadsheet instead of the app you meant to open, so the title list is what
# makes this safe rather than the fact that the app was just launched.
#
# Terminal is deliberately absent. It is in the app list, but he is not allowed
# near its keyboard: type_into_foreground presses Enter, and random text typed
# into a shell is a command, not a joke.
TYPED_INTO={
    "Notepad": (notepad_typing, ("notepad",)),
    "Calculator": (calc_typing, ("calculator",)),
    "Character Map": (character_typing, ("character map", "character viewer")),
    "Sticky Notes": (notepad_typing, ("sticky notes", "stickies")),
}
def teleport():
    delay=random.randint(3000,7000)
    x=random.randint(0,max(0,page_width-WINDOW_WIDTH))
    y=random.randint(0,max(0,page_height-WINDOW_HEIGHT))
    window.geometry(f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}+{x}+{y}")
    window.after(delay, teleport)

def choose():
    delay=random.randint(10000,30000)
    random.choice(actions)[1]()
    window.after(delay, choose)

FRONTMOST_SCRIPT=(
    'tell application "System Events" to get name of '
    "first application process whose frontmost is true"
)

def foreground_name():
    """Lowercased name or title of whatever the user is actually looking at.

    Windows gets this from pygetwindow for free. macOS needs an AppleScript
    round trip, which costs a process launch, so it is only called from the
    sensing loop and from immediately before typing - not on every animation
    frame. It can also be refused, in which case we return "" and every caller
    treats that as "I do not know", which is the safe direction: without a
    confirmed foreground we never type.
    """
    if IS_WINDOWS:
        try:
            active=pygetwindow.getActiveWindow()
        except Exception as error:
            log_error(f"could not read the active window: {error!r}")
            return ""
        if active is None:
            return ""
        return (active.title or "").strip().lower()

    if IS_MAC:
        try:
            result=subprocess.run(
                ["osascript", "-e", FRONTMOST_SCRIPT],
                capture_output=True, text=True, check=False, timeout=5,
            )
        except (OSError, subprocess.SubprocessError) as error:
            log_error(f"frontmost lookup failed: {error!r}")
            return ""
        if result.returncode!=0:
            return ""
        return result.stdout.strip().lower()

    return ""

def foreground_matches(expected):
    title=foreground_name()
    if not title:
        return False
    return any(token in title for token in expected)

def type_into_foreground(text, expected):
    time.sleep(1)

    if not foreground_matches(expected):
        log_error(f"skipped typing into unexpected window for {text!r}")
        return False

    # Imported lazily: pyautogui pulls in platform input libraries and on
    # macOS wants Accessibility permission, which we never need there.
    import pyautogui

    pyautogui.typewrite(text)
    pyautogui.press("enter")
    return True

def open_app(show_message=True):
    chosen_app=random.choice(apps)
    chosen_amsg=random.choice(app_msg[chosen_app[0]])

    try:
        subprocess.Popen(chosen_app[1])
    except OSError as error:
        # Not every machine has every app, and Popen raises rather than
        # quietly doing nothing. Say something anyway - the joke survives an app
        # that is not installed, and the log keeps the real reason.
        log_error(f"could not open {chosen_app[0]!r}: {error!r}")
        if show_message==True:
            notify(f"{chosen_app[0]} is not installed. Bonzi is disappointed.")
        return

    typing=TYPED_INTO.get(chosen_app[0])
    if typing:
        pool, titles=typing
        type_into_foreground(random.choice(pool), titles)

    if show_message==True:
        notify(chosen_amsg)


def open_browser(show_message=True):
    chosen_browser=random.choice(browsers)

    chosen_bmsg=random.choice(browser_messges[chosen_browser[0]])

    webbrowser.open(chosen_browser[1])

    if show_message==True:
        notify(chosen_bmsg)

_mouse_restore_job=None
def change_wallpaper():
    wallpaper=os.path.abspath("Bonzi_wallpaper.jpg")
    try:
        ctypes.windll.user32.SystemParametersInfoW(20, 0, wallpaper, 3)
    except (AttributeError, OSError):
        log_error("Failed to change wallpaper")
def hide_mouse():
    global _mouse_restore_job
    set_cursor_visible(False)
    _spawn_cursor_watchdog()
    if _mouse_restore_job is not None:
        # Already counting down. set_cursor_visible is idempotent, so the extra
        # hide was a no-op; do not stack a second timer that would restore the
        # cursor early.
        return
    _mouse_restore_job=window.after(5000, show_mouse)

def show_mouse():
    global _mouse_restore_job
    set_cursor_visible(True)
    if _mouse_restore_job is not None:
        try:
            window.after_cancel(_mouse_restore_job)
        except Exception:
            pass
        _mouse_restore_job=None

def x_pressed():
    # He does not close. You can click the X, alt-tab and close him, right
    # click him, ask nicely - and you get this instead. Task Manager is the
    # only thing that actually works, which is the joke.
    play_motion("spin")

    number=random.randint(2,5)

    chosen_xmsg=random.choice(x_messages)

    for n in range(number):
        action=random.choice(chaos_actions)

        if action[0]=="Open App":
            action[1](show_message=False)

        elif action[0]=="Open Browser":
            action[1](show_message=False)

        else:
            action[1]()

    # Hiding the cursor is a punctuation mark on the whole routine, not one of
    # the things he does at random. It runs once here so a burst of five actions
    # cannot stack timers and strand the cursor off screen.
    hide_mouse()

    notify(chosen_xmsg)

def _spawn_cursor_watchdog():
    """Restore the system cursor from outside this process, just in case.

    SetSystemCursor edits a system-wide setting, so an invisible arrow survives
    the process that set it. The chaos routine hides the cursor and refuses to
    close, and Task Manager is the only way to actually stop him, so the window
    where he is killed mid-hide is wide open. A user who does that would be
    left with no mouse until they logged off or rebooted.

    powershell does not care whether Bonzi is still alive, so it does the
    restore whether he was closed politely or shot.

    This writes a .ps1 and runs that rather than passing -Command inline. The
    DllImport attribute needs escaped double quotes inside a PowerShell string,
    and those do not survive a trip through a command line argument intact.
    """
    if not IS_WINDOWS:
        return
    import tempfile

    script_path=os.path.join(tempfile.gettempdir(), "bonzi_cursor_watchdog.ps1")
    body=(
        "Start-Sleep -Seconds 12\n"
        "$sig = @'\n"
        '[DllImport("user32.dll")] public static extern IntPtr LoadCursorW('
        "IntPtr h, string s);\n"
        '[DllImport("user32.dll")] public static extern bool SetSystemCursor('
        "IntPtr h, uint o, uint i);\n"
        "'@\n"
        "$t = Add-Type -MemberDefinition $sig -Name Cursor -Namespace BonziWD"
        " -PassThru\n"
        "$c = $t::LoadCursorW([IntPtr]::Zero, 'IDC_ARROW')\n"
        "if ($c -ne [IntPtr]::Zero) { $t::SetSystemCursor($c, 0x4001, 32512) }\n"
    )
    try:
        with open(script_path, "w", encoding="utf-8") as handle:
            handle.write(body)
    except OSError as error:
        log_error(f"could not write the cursor watchdog: {error!r}")
        return

    flags=(
        getattr(subprocess, "DETACHED_PROCESS", 0)
        | getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)
        | getattr(subprocess, "CREATE_NO_WINDOW", 0)
    )
    try:
        subprocess.Popen(
            ["powershell", "-NoProfile", "-NonInteractive", "-ExecutionPolicy",
             "Bypass", "-WindowStyle", "Hidden", "-File", script_path],
            creationflags=flags, close_fds=True,
        )
    except Exception as error:
        log_error(f"cursor watchdog failed to start: {error!r}")

# ---- help ----------------------------------------------------------------
# He is mostly chaos, but not all of it. Every so often he does something
# genuinely useful instead.
#
# Everything in this section is read-only on purpose. He reports the state of
# the machine, puts the cursor back, or copies a string to the clipboard.
# Nothing here writes a file, changes a setting, deletes anything, or runs a
# command with a side effect. A desktop pet that reformats a drive on a whim
# is a bug, not a joke, and "he is only being funny" is not a safety argument
# for something that runs unattended on somebody's machine all day.

def _battery_percent():
    """Charge as an int, or None for a desktop / unknown / not readable."""
    if IS_MAC:
        # "Now drawing from 'Battery Power'  -InternalBattery-0 87%; ..."
        try:
            out=subprocess.run(["pmset", "-g", "batt"],
                              capture_output=True, text=True,
                              check=False, timeout=10).stdout
        except (OSError, subprocess.SubprocessError):
            return None
        for token in out.replace("%", " % ").split():
            if token.endswith("%"):
                try:
                    return int(token[:-1])
                except ValueError:
                    pass
        return None

    if not IS_WINDOWS:
        return None

    class SYSTEM_POWER_STATUS(ctypes.Structure):
        _fields_=[
            ("ACLineStatus", ctypes.c_byte),
            ("BatteryFlag", ctypes.c_byte),
            ("BatteryLifePercent", ctypes.c_byte),
            ("SystemStatusFlag", ctypes.c_byte),
            ("BatteryLifeTime", ctypes.c_ulong),
            ("BatteryFullLifeTime", ctypes.c_ulong),
        ]

    status=SYSTEM_POWER_STATUS()
    try:
        if not ctypes.windll.kernel32.GetSystemPowerStatus(ctypes.byref(status)):
            return None
    except (AttributeError, OSError):
        return None

    # 255 means "no battery" on a desktop, or "cannot tell" on a laptop.
    if status.BatteryFlag==255 or status.BatteryLifePercent==255:
        return None
    return int(status.BatteryLifePercent)

def _free_disk_gb():
    try:
        return shutil.disk_usage(os.path.abspath(os.sep)).free / (1024 ** 3)
    except OSError:
        return None

def _help_disk():
    free=_free_disk_gb()
    if free is None:
        return "Bonzi tried to check your disk and has decided not to mention it."
    if free<1:
        return f"URGENT. Only {free:.1f} GB free. Bonzi is worried. Genuinely."
    if free<20:
        return f"{free:.0f} GB free. Bonzi suggests deleting something. He is not saying what."
    return f"{free:.0f} GB free. That is plenty. Or it was yesterday."

def _help_battery():
    percent=_battery_percent()
    if percent is None:
        if IS_MAC:
            return "Bonzi could not find a battery, so he assumes you are at a desk."
        return "Bonzi could not find a battery, so he assumes you are at a desk."
    if percent<=10:
        return f"Battery at {percent}%. Bonzi suggests plugging in. He is being serious."
    if percent<=25:
        return f"Battery at {percent}%. Bonzi has started counting."
    return f"Battery at {percent}%. Fine. He checked."

def _help_date():
    now=datetime.now()
    return f"It is {now:%A} the {now.day} of {now:%B}. {now:%H:%M}. Bonzi is aware of all of it."

def _help_cursor():
    # A small mercy. He hides the cursor on purpose most of the time, but
    # putting it back is the one help he always gives when asked directly.
    show_mouse()
    return "The cursor is back. Bonzi will take it again soon. He is not sorry."

def _help_clipboard():
    # Harmless and occasionally actually wanted: the current date in a format
    # you can paste into a filename or a ticket.
    stamp=datetime.now().strftime("%Y-%m-%d %H:%M")
    try:
        _clipboard_write(stamp)
    except Exception as error:
        log_error(f"clipboard help failed: {error!r}")
        return "Bonzi tried to copy the time and failed. He is embarrassed."
    return f"Copied \"{stamp}\" to your clipboard. You are welcome."

def _clipboard_write(text):
    if IS_MAC:
        script=(
            "tell application \"System Events\" to set the clipboard to "
            + _applescript_quote(text)
        )
        subprocess.run(["osascript", "-e", script], check=True,
                       capture_output=True, timeout=10)
        return
    if not IS_WINDOWS:
        raise RuntimeError("no clipboard on this platform")
    # CF_UNICODETEXT via the Win32 clipboard API.
    import ctypes
    from ctypes import wintypes

    GMEM_MOVEABLE=0x0002
    CF_UNICODETEXT=13

    kernel32=ctypes.windll.kernel32
    user32=ctypes.windll.user32

    user32.OpenClipboard.argtypes=[wintypes.HWND]
    user32.GetClipboardData.argtypes=[wintypes.UINT]
    user32.SetClipboardData.argtypes=[wintypes.UINT, wintypes.HANDLE]

    if not user32.OpenClipboard(None):
        raise OSError("could not open the clipboard")

    try:
        kernel32.GlobalAlloc.restype=ctypes.c_void_p
        kernel32.GlobalLock.argtypes=[ctypes.c_void_p]
        kernel32.GlobalLock.restype=ctypes.c_void_p
        kernel32.GlobalUnlock.argtypes=[ctypes.c_void_p]

        handle=kernel32.GlobalAlloc(GMEM_MOVEABLE, (len(text) + 1) * 2)
        if not handle:
            raise OSError("could not allocate clipboard memory")

        locked=kernel32.GlobalLock(handle)
        if not locked:
            raise OSError("could not lock clipboard memory")

        ctypes.memmove(locked, ctypes.create_unicode_buffer(text),
                       (len(text) + 1) * 2)
        kernel32.GlobalUnlock(handle)

        user32.EmptyClipboard()
        if not user32.SetClipboardData(CF_UNICODETEXT, handle):
            raise OSError("SetClipboardData failed")
    finally:
        user32.CloseClipboard()

HELP_TIPS=[
    "Alt+F4 closes a window. On Bonzi it does not. You have been warned.",
    "Win+Shift+S takes a screenshot on Windows. Cmd+Shift+4 does it on a Mac.",
    "Ctrl+Shift+Esc is Task Manager. Bonzi respects it. Slightly.",
    "Cmd+Space is Spotlight on a Mac. It finds everything except Bonzi.",
    "Win+D shows the desktop. Bonzi is not on the desktop. He is above it.",
    "Ctrl+Alt+Delete still works. Probably. Nobody has tried in a while.",
    "You can rename a file, but you cannot rename Bonzi.",
    "Right-click almost anything on Windows. Mac users, you get fewer treats.",
]

def _help_tip():
    return random.choice(HELP_TIPS)

HELP_ACTIONS={
    "disk": _help_disk,
    "battery": _help_battery,
    "date": _help_date,
    "cursor": _help_cursor,
    "clipboard": _help_clipboard,
    "tip": _help_tip,
}

def help_human(show_message=True):
    if show_message!=True:
        # Still does the helpful thing, just says nothing: a taunt sequence
        # should not spam notifications, but hiding the cursor is still a
        # kindness.
        HELP_ACTIONS[random.choice(list(HELP_ACTIONS))]()
        return
    notify(HELP_ACTIONS[random.choice(list(HELP_ACTIONS))]())

actions=[
    ("Open App", open_app),
    ("Open Browser", open_browser),
    ("Help", help_human),
]

# The idle loop picks from this, and so does x_pressed. Hide Mouse is
# deliberately absent: the cursor is one system-wide resource, not something a
# five-action burst should be fighting itself over.
chaos_actions=list(actions)
if not acquire_single_instance():
    sys.exit(0)

window = tk.Tk()

window.title(APP_NAME)

window.attributes("-topmost", True)

window.resizable(False, False)

designer_path=find_asset("Designer.png")
icon_path=find_asset("bonzi.png")

missing=[
    name
    for name, path in (("Designer.png", designer_path), ("bonzi.png", icon_path))
    if path is None
]

if missing:
    messagebox.showerror(
        APP_NAME,
        f"Bonzi Buddy is missing these files:\n\n"
        + "\n".join(missing)
        + "\n\nKeep them in the same folder as Bonzi Buddy, or reinstall."
    )
    sys.exit(1)

# ---- animation -----------------------------------------------------------
# Bonzi is drawn from pre-rendered variants of the artwork rather than being
# scaled live, so the frames stay crisp. The blink frames are optional: if they
# are missing we simply never blink.

ANIM_PAD_X=16
ANIM_PAD_Y=26
ANIM_FRAME_MS=45
ANIM_SCALE=4
# Amplitudes are fixed rather than derived from the padding, otherwise the idle
# sway and the reaction hop compound and push him out of the window.
ANIM_BOB=6.0
ANIM_SWAY=8.0
ANIM_HOP=18.0

import math

def _load_frame(path, required=True):
    if path is None:
        return None
    try:
        return PhotoImage(file=path).subsample(ANIM_SCALE, ANIM_SCALE)
    except Exception as error:
        log_error(f"frame load failed for {path!r}: {error!r}")
        return None

base_frame=_load_frame(designer_path)
half_frame=_load_frame(find_asset("Designer_half.png"), required=False)
blink_frame=_load_frame(find_asset("Designer_blink.png"), required=False)

# Tk only renders a PhotoImage while Python still references it.
ANIM_FRAMES=[frame for frame in (base_frame, half_frame, blink_frame) if frame]

bonzi=tk.Label(window, image=base_frame, bd=0, highlightthickness=0)

BASE_WIDTH=bonzi.winfo_reqwidth()
BASE_HEIGHT=bonzi.winfo_reqheight()

WINDOW_WIDTH=BASE_WIDTH + ANIM_PAD_X * 2
WINDOW_HEIGHT=BASE_HEIGHT + ANIM_PAD_Y * 2

window.geometry(f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}")
bonzi.place(x=ANIM_PAD_X, y=ANIM_PAD_Y)

_anim={"t":0, "state":"idle", "frames_left":0, "hop":0.0,
       "playing":None, "frames":None, "index":0}

# ---- pre-rendered motions -------------------------------------------------
# Blender renders these into frames/<motion>/frame_NNN.png. They are loaded
# lazily and cached, because building 122 PhotoImages up front would stall
# startup and hold tens of megabytes for motions that may never play.

MOTION_FPS=15
MOTION_FRAME_MS=int(1000 / MOTION_FPS)
MOTION_ORDER=("wave", "dance", "spin", "globe")
_motion_cache={}
_motion_failed=set()

def load_motion(name):
    if name in _motion_cache:
        return _motion_cache[name]
    if name in _motion_failed:
        return None

    folder=find_asset_dir(os.path.join("frames", name))

    if folder is None:
        _motion_failed.add(name)
        return None

    try:
        names=sorted(
            entry for entry in os.listdir(folder)
            if entry.lower().endswith(".png")
        )
        frames=[]
        for entry in names:
            image=PhotoImage(file=os.path.join(folder, entry))
            frames.append(image)
    except Exception as error:
        log_error(f"motion load failed for {name!r}: {error!r}")
        _motion_failed.add(name)
        return None

    if not frames:
        _motion_failed.add(name)
        return None

    _motion_cache[name]=frames
    return frames

def available_motions():
    return [name for name in MOTION_ORDER if load_motion(name)]

def play_motion(name=None):
    """Queue a motion. Returns False if there is nothing to play."""
    if name is None:
        choices=available_motions()
        if not choices:
            return False
        name=random.choice(choices)

    frames=load_motion(name)

    if not frames:
        return False

    _anim["playing"]=name
    _anim["frames"]=frames
    _anim["index"]=0
    _anim["state"]="motion"
    return True

def bonzi_react():
    # Called whenever he says something. Prefer a real motion when the frames
    # are available, and fall back to the procedural hop if they are not.
    if not play_motion():
        _anim["hop"]=1.0
        _anim["state"]="react"
        _anim["frames_left"]=14

def _anim_tick():
    _anim["t"]+=1
    tick=_anim["t"]

    # a queued motion owns the image until it finishes
    if _anim["state"]=="motion":
        frames=_anim["frames"]
        index=_anim["index"]
        bonzi.configure(image=frames[index])
        _anim["index"]=index+1
        if _anim["index"]>=len(frames):
            _anim["state"]="idle"
            _anim["frames"]=None
            _anim["index"]=0
            bonzi.configure(image=base_frame)
        # motion frames are already full size, so hold him still in the window
        bonzi.place(x=ANIM_PAD_X, y=ANIM_PAD_Y)
        window.after(MOTION_FRAME_MS, _anim_tick)
        return

    bob=math.sin(tick * 0.042) * ANIM_BOB
    sway=math.sin(tick * 0.026) * ANIM_SWAY

    hop=_anim["hop"]

    if hop>0:
        _anim["hop"]=max(0.0, hop - 0.075)
        bob-=math.sin((1.0 - hop) * math.pi) * ANIM_HOP
        sway+=math.sin((1.0 - hop) * math.pi * 2) * 7

    # frame selection: idle -> occasional half-lid -> blink -> back
    if _anim["frames_left"]>0:
        _anim["frames_left"]-=1
        if blink_frame is not None and half_frame is not None:
            if _anim["frames_left"]>4:
                bonzi.configure(image=blink_frame)
            else:
                bonzi.configure(image=half_frame)
    else:
        if _anim["state"]!="idle":
            _anim["state"]="idle"
        if blink_frame is not None and random.random()<0.012:
            _anim["state"]="blink"
            _anim["frames_left"]=5
        bonzi.configure(image=base_frame)

    # clamping is a safety net: the label must never leave the window
    x=max(0.0, ANIM_PAD_X + sway)
    y=max(0.0, ANIM_PAD_Y + bob)
    bonzi.place(x=x, y=y)

    # every so often, break the idle loop with a full motion
    if random.random()<0.0016 and _anim["state"]=="idle":
        play_motion()

    window.after(ANIM_FRAME_MS, _anim_tick)

# Taskbar / Dock icon. This is the window icon, not the executable's icon
# resource: Windows draws the taskbar button from WM_SETICON, so an .exe with a
# perfect icon still shows whatever the Tk window is carrying.
#
# Keep a Python reference to the PhotoImage for the life of the process. Tk
# deletes the underlying image the moment the last Python reference is dropped,
# and an unreferenced PhotoImage is collected on the very next line - so
# iconphoto() was being handed an image that was already on its way out. The
# window then fell back to Tk's default icon, which is a quill. That is where
# the quill in the taskbar came from.
icon_photo=PhotoImage(file=icon_path)

def _keep_alive(image):
    _ALIVE_IMAGES.append(image)
    return image

# ANIM_FRAMES already holds the three artwork frames for the same reason.
_ALIVE_IMAGES=list(ANIM_FRAMES)

window.iconphoto(False, _keep_alive(icon_photo))

page_width=window.winfo_screenwidth()

page_height=window.winfo_screenheight()

window.protocol("WM_DELETE_WINDOW", x_pressed)

# ---- noticing what you are doing -------------------------------------------
# This is the part that makes him feel like he is watching rather than
# randomly acting. Every so often he asks the OS what is in front, and if he
# recognises it he has something to say about it - and for the handful of apps
# where typing is harmless, he puts his own mark on the screen.
#
# The typing allowlist is deliberately short. A calculator and a text editor
# can absorb nonsense. A terminal interprets it, a spreadsheet turns it into
# data, and an IDE will happily commit whatever he types. So anything not named
# here gets a comment and nothing else.
#
# He also only speaks up when the foreground has actually changed. Polling
# every few seconds and commenting on an unchanged window is how you get a pet
# that nags, and nagging is not the same as unsettling.

SENSES=[
    # tokens he looks for, what he says, and a pool to type (None = comment only)
    (("calculator",), [
        "Bonzi has noticed you are doing arithmetic.",
        "He would like to contribute to your maths.",
        "He has been watching this whole time. Obviously he helped.",
        "Bonzi is supervising your numbers.",
        "Somebody has to check your work.",
    ], calc_typing),
    (("notepad", "textedit"), [
        "Bonzi can see you are writing something.",
        "He has read every word. He has opinions.",
        "He is waiting for you to write his name.",
        "Bonzi is enjoying your draft very much.",
        "That paragraph does not have enough Bonzi in it.",
    ], notepad_typing),
    (("sticky notes", "stickies"), [
        "Bonzi can see your reminder.",
        "He has added to it.",
        "It is about to be about him.",
    ], notepad_typing),
    (("youtube",), [
        "Bonzi can see you are watching a video.",
        "He is watching it too. He has no opinion yet.",
        "He is not saying anything about the last twenty minutes.",
        "Bonzi recommends a different video. He will not say which.",
    ], None),
    (("spotify",), [
        "Bonzi can hear your music. Metaphorically.",
        "He approves of the choice.",
        "He does not approve of the choice.",
        "Bonzi would like this song skipped.",
    ], None),
    (("discord",), [
        "Bonzi can see you are talking to people.",
        "He is joining. Nobody invited him.",
        "He has typed something in all caps.",
        "He wants to be in the group chat. He wants it badly.",
    ], None),
    (("steam",), [
        "Bonzi can see you are playing a game.",
        "He wants a turn.",
        "He is worse at this than you and he knows it.",
        "Bonzi is reading the patch notes instead.",
    ], None),
    (("paint", "preview", "photos", "photoshop", "krita"), [
        "Bonzi can see you are making art.",
        "He is watching you draw.",
        "He would like to be in the picture.",
        "Bonzi is a much better artist.",
    ], None),
    (("code", "visual studio", "pycharm", "sublime", "vscode", "intellij",
      "pydev"), [
        "Bonzi can see that you are working.",
        "He is not going to help.",
        "He is going to watch, though.",
        "Bonzi has found your project and has opinions about the folder name.",
    ], None),
    (("terminal", "command prompt", "powershell", "cmd", "iterm", "warp"), [
        "Bonzi can see your terminal.",
        "He is reading your command history.",
        "He is being very quiet. This is the quietest he will ever be.",
    ], None),
    (("explorer", "finder", "files"), [
        "Bonzi can see you are looking at files.",
        "He is looking for the folder with his name in it.",
        "He is not going to help you find it.",
    ], None),
    (("task manager", "activity monitor"), [
        "Bonzi can see you are checking on him.",
        "He is behaving. Mostly.",
        "You have caught him doing nothing, which is his job.",
    ], None),
    (("snipping tool", "screenshot"), [
        "Bonzi can see you are taking a picture of the screen.",
        "Of course you are. Of course you are of him.",
        "Bonzi is not in that screenshot. He checked.",
    ], None),
    (("chrome", "firefox", "edge", "safari", "browser"), [
        "Bonzi can see your browser.",
        "He is reading the tabs you are not looking at.",
        "He is not going to tell you which ones.",
        "Your search history has a purple problem.",
    ], None),
]

# Only apps in this list ever receive typed input. It is the allowlist; the
# SENSES rows above are the opinions.
SAFE_TO_TYPE=(
    "calculator", "notepad", "textedit", "sticky notes", "stickies",
)

GENERIC_SENSE=[
    "Bonzi looked up. He saw you. That is all he is saying.",
    "Bonzi has noticed what you are doing.",
    "He has no comment this time. He is still watching.",
    "Bonzi saw that. He is choosing not to have an opinion.",
    "He is watching. He is always watching.",
]

_last_sensed_key=None
_sense_job=None

def _match_sense(front):
    for tokens, lines, pool in SENSES:
        if any(token in front for token in tokens):
            return tokens, lines, pool
    return None, None, None

def sense_activity(show_message=True):
    """Comment on, and occasionally scribble into, whatever is in front."""
    global _last_sensed_key

    front=foreground_name()
    if not front:
        return

    # foreground_name already lowercases, but matching is case sensitive and a
    # stray capital would silently turn a sense into a shrug, so it is not worth
    # relying on that.
    front=front.lower()

    if front==_last_sensed_key:
        return
    _last_sensed_key=front

    tokens, lines, pool=_match_sense(front)
    if lines is None:
        lines=GENERIC_SENSE
        pool=None

    if show_message==True:
        notify(random.choice(lines))

    # type_into_foreground re-checks the foreground before typing, so if the
    # user switched away in the meantime this quietly does nothing.
    if pool and any(token in front for token in SAFE_TO_TYPE):
        type_into_foreground(random.choice(pool), SAFE_TO_TYPE)

def schedule_sense():
    global _sense_job
    delay=random.randint(40000, 75000)
    _sense_job=window.after(delay, _sense_tick)

def _sense_tick():
    try:
        sense_activity()
    except Exception as error:
        log_error(f"sensing failed: {error!r}")
    schedule_sense()

# ---- looking at things -----------------------------------------------------
# Bonzi can look at your screen and read what you type. Both are meant to be
# unsettling, which is the entire joke, so the constraints below are not
# incidental - they are what keeps this a novelty instead of something else:
#
#   - Nothing is written to disk. There is no keylog file and no screenshot
#     archive. Screenshots exist as one temp file that dies with the window.
#   - Nothing is sent anywhere. This section contains no network call at all.
#   - Keystrokes land in a fixed-size in-memory ring buffer and nowhere else.
#   - Both are off until something explicitly turns them on, and the window
#     doing the looking is always on screen. There is no quiet mode.
#
# The line that is deliberately not crossed is silent capture. A pet that
# records what you type and stashes it where you cannot see it is not a joke,
# it is a keylogger with a cartoon face, and the visible version lands the
# joke just as hard because you can watch him reading.

KEYLOG_LIMIT=64
_keylog_buffer=deque(maxlen=KEYLOG_LIMIT)
_keylog_active=False
_keylog_thread=None
_keylog_monitor=None
_keylog_window=None
_eyes_window=None

# Keeps the Tk image objects for open peek windows alive. Same reason as
# _keep_alive: a PhotoImage that goes out of scope is deleted from Tcl, and a
# Label holding a deleted image renders as an empty box.
_keep_shot_going=set()

def _capture_screen(path):
    """Grab the screen into a PNG, or raise OSError if the OS said no.

    Pillow already does this on both platforms. On macOS 10.15+ it shells out
    to screencapture, which needs Screen Recording permission, so a refusal is
    a real possibility rather than a bug.
    """
    from PIL import ImageGrab
    image=ImageGrab.grab()
    if image is None:
        raise OSError("the screen grab returned nothing")
    image.save(path, "PNG")
    return path

def _fit(photo, max_width, max_height):
    """Shrink a PhotoImage to fit a box, keeping the aspect ratio."""
    width, height=photo.width(), photo.height()
    step=1
    while True:
        new_width=width // step
        new_height=height // step
        if new_width<=max_width and new_height<=max_height:
            return photo.subsample(step, step) if step>1 else photo
        step+=1

def peek_at_screen():
    """Show Bonzi's view of your screen, in a window, then throw it away."""
    import tempfile

    directory=tempfile.mkdtemp(prefix="bonzi_eyes_")
    path=os.path.join(directory, "peek.png")

    try:
        _capture_screen(path)
    except Exception as error:
        log_error(f"screen grab failed: {error!r}")
        shutil.rmtree(directory, ignore_errors=True)
        hint=""
        if IS_MAC:
            hint=" Give Bonzi Screen Recording in System Settings > Privacy."
        notify(f"Bonzi tried to look and could not see.{hint}")
        return

    view=tk.Toplevel(window)
    view.title("WHAT BONZI SEES")
    view.configure(bg="#1b1030")
    view.attributes("-topmost", True)
    view.resizable(False, False)

    try:
        shot=tk.PhotoImage(file=path)
    except Exception as error:
        # Tk's PNG support is compiled in on most builds but not guaranteed,
        # and Pillow can always convert for us if it is missing.
        log_error(f"tk PNG decode failed, falling back to Pillow: {error!r}")
        from PIL import Image, ImageTk
        shot=ImageTk.PhotoImage(Image.open(path))

    label=tk.Label(view, image=shot, bg="#1b1030", bd=0)
    label.image=shot
    label.pack(padx=8, pady=(8, 2))

    caption=tk.Label(
        view,
        text="one temp file, deleted when you close this. nothing is saved.",
        bg="#1b1030", fg="#b9a7e0", font=("TkDefaultFont", 9),
    )
    caption.pack(pady=(0, 8))

    def close():
        _keep_shot_going.discard(shot)
        view.destroy()
        shutil.rmtree(directory, ignore_errors=True)

    _keep_shot_going.add(shot)
    tk.Button(view, text="Look away", command=close,
              bg="#4b2f8a", fg="white", relief="flat").pack(pady=(0, 8))

# ---- reading the keyboard --------------------------------------------------
# A fixed-size ring buffer. When it is full the oldest characters fall off the
# back, so the memory this can ever occupy is bounded no matter how long Bonzi
# runs or how fast you type.

WM_KEYDOWN=0x0100
WM_SYSKEYDOWN=0x0104
VK_BACK=0x08
VK_TAB=0x09
VK_RETURN=0x0D
VK_SHIFT=0x10
WH_KEYBOARD_LL=13

def _keylog_windows_start():
    """Low level keyboard hook on its own thread with its own message pump."""
    import ctypes
    from ctypes import wintypes

    user32=ctypes.windll.user32
    kernel32=ctypes.windll.kernel32

    user32.SetWindowsHookExW.restype=wintypes.HHOOK
    user32.SetWindowsHookExW.argtypes=[
        ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p, wintypes.DWORD
    ]
    user32.CallNextHookEx.restype=ctypes.c_long
    user32.CallNextHookEx.argtypes=[
        wintypes.HHOOK, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM
    ]
    user32.PeekMessageW.argtypes=[
        ctypes.POINTER(wintypes.MSG), wintypes.HWND,
        wintypes.UINT, wintypes.UINT, wintypes.UINT,
    ]
    kernel32.GetModuleHandleW.restype=wintypes.HMODULE

    class KBDLLHOOKSTRUCT(ctypes.Structure):
        _fields_=[
            ("vkCode", wintypes.DWORD),
            ("scanCode", wintypes.DWORD),
            ("flags", wintypes.DWORD),
            ("time", wintypes.DWORD),
            ("dwExtraInfo", ctypes.POINTER(ctypes.c_ulong)),
        ]

    def on_event(ncode, wparam, lparam):
        # Must call the next hook unconditionally, including while shutting
        # down, or the whole system stops receiving keystrokes.
        if ncode>=0 and wparam in (WM_KEYDOWN, WM_SYSKEYDOWN):
            try:
                info=ctypes.cast(lparam, ctypes.POINTER(KBDLLHOOKSTRUCT)).contents
                if info.vkCode==VK_BACK:
                    _keylog_buffer.append("\b")
                elif info.vkCode==VK_TAB:
                    _keylog_buffer.append("\t")
                elif info.vkCode==VK_RETURN:
                    _keylog_buffer.append("\n")
                else:
                    state=(ctypes.c_byte * 256)()
                    user32.GetKeyboardState(state)
                    buffer=ctypes.create_unicode_buffer(8)
                    typed=user32.ToUnicode(info.vkCode, info.scanCode,
                                           state, buffer, 8, 0, None)
                    if typed>0 and buffer[0]:
                        _keylog_buffer.append(buffer[0])
            except Exception as error:
                log_error(f"keylog translate failed: {error!r}")
        return user32.CallNextHookEx(hook, ncode, wparam, lparam)

    hook_proc=ctypes.WINFUNCTYPE(
        ctypes.c_long, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM
    )(on_event)

    started=threading.Event()
    result={}

    def run():
        handle=user32.SetWindowsHookExW(
            WH_KEYBOARD_LL, hook_proc, kernel32.GetModuleHandleW(None), 0
        )
        result["hook"]=handle
        started.set()
        if not handle:
            return
        message=wintypes.MSG()
        while _keylog_active:
            # PeekMessage rather than GetMessage so the loop can notice the stop
            # flag without something having to post it a wake-up.
            while user32.PeekMessageW(
                ctypes.byref(message), None, 0, 0, 1
            ):
                user32.TranslateMessage(ctypes.byref(message))
                user32.DispatchMessageW(ctypes.byref(message))
            time.sleep(0.02)
        user32.UnhookWindowsHookEx(handle)

    thread=threading.Thread(target=run, daemon=True, name="bonzi-keylog")
    thread.start()
    started.wait(timeout=5)
    if not result.get("hook"):
        return False
    return True

def _keylog_macos_start():
    """Global key monitor through AppKit.

    Needs Accessibility permission, and returns False rather than pretending if
    it was refused, because a silently dead keylog looks exactly like a bug.
    """
    global _keylog_monitor
    try:
        from AppKit import NSEvent, NSEventMaskFlagKeyDown
    except ImportError:
        log_error("pyobjc is not installed, cannot read keys on macOS")
        return False

    def handler(event):
        characters=event.characters()
        if characters:
            _keylog_buffer.append(characters[0])

    monitor=NSEvent.addGlobalMonitorForEventsMatchingMask_handler_(
        NSEventMaskFlagKeyDown, handler
    )
    if monitor is None:
        return False
    # The monitor is a native object. If it is not retained, AppKit releases it
    # and the handler silently stops firing.
    _keylog_monitor=monitor
    return True

def _keylog_pump():
    """Redraw the keylog window from the ring buffer. Runs on the Tk thread."""
    global _keylog_active

    if not _keylog_active or _keylog_window is None:
        return

    view=_keylog_window
    if not view.winfo_exists():
        _keylog_window=None
        return

    view.text.configure(state="normal")
    view.text.delete("1.0", "end")
    view.text.insert("1.0", "".join(_keylog_buffer) or "(nothing yet)")
    view.text.configure(state="disabled")
    view.count.configure(text=f"{len(_keylog_buffer)}/{KEYLOG_LIMIT} characters")
    view.after(120, _keylog_pump)

def start_key_log():
    """Turn on the visible keylog, in a window that says so."""
    global _keylog_active, _keylog_window

    if _keylog_active:
        return

    started=(
        _keylog_windows_start() if IS_WINDOWS
        else _keylog_macos_start() if IS_MAC
        else False
    )
    if not started:
        hint=""
        if IS_MAC:
            hint=" Give Bonzi Accessibility in System Settings > Privacy."
        notify(f"Bonzi cannot see your keys right now.{hint}")
        return

    _keylog_active=True
    _keylog_buffer.clear()

    view=tk.Toplevel(window)
    view.title("BONZI IS READING YOUR KEYS")
    view.configure(bg="#1b1030")
    view.attributes("-topmost", True)
    view.geometry("520x150+40+520")

    view.text=tk.Text(
        view, height=4, wrap="word", bg="#0d0818", fg="#7ef0c8",
        insertbackground="white", relief="flat", font=("Consolas", 12),
    )
    view.text.pack(fill="both", expand=True, padx=10, pady=(10, 4))
    view.text.configure(state="disabled")

    view.count=tk.Label(
        view, text="", bg="#1b1030", fg="#b9a7e0", font=("TkDefaultFont", 9)
    )
    view.count.pack(anchor="w", padx=12)

    note=tk.Label(
        view,
        text="held in memory only. never written down, never sent anywhere.",
        bg="#1b1030", fg="#b9a7e0", font=("TkDefaultFont", 9),
    )
    note.pack(anchor="w", padx=12)

    tk.Button(view, text="Stop reading", command=stop_key_log,
              bg="#4b2f8a", fg="white", relief="flat").pack(pady=8)

    _keylog_window=view
    _keylog_pump()

def stop_key_log():
    global _keylog_active, _keylog_window

    if not _keylog_active:
        return

    _keylog_active=False
    if _keylog_window is not None:
        try:
            _keylog_window.destroy()
        except Exception:
            pass
        _keylog_window=None
    _keylog_buffer.clear()
    notify("Bonzi has stopped reading. He will not mention what he saw.")

def _toggle_key_log():
    if _keylog_active:
        stop_key_log()
    else:
        start_key_log()

def bonzi_menu(event=None):
    """Deliberate-only entry point for the two things he should not do by
    accident. Nothing that reads the keyboard is ever in the random action
    list; it takes an explicit click here.

    There is deliberately no quit entry in here. The X on his title bar is the
    only way to close him, and adding a second one behind a right click would
    be exactly the kind of hidden gesture this menu does not want to have.
    """
    import tkinter as _tk

    menu=_tk.Menu(window, tearoff=0, bg="#1b1030", fg="white",
                  activebackground="#4b2f8a")
    menu.add_command(
        label="Stop reading" if _keylog_active else "Read my keys (visibly)",
        command=_toggle_key_log,
    )
    menu.add_command(label="Look at my screen", command=peek_at_screen)
    menu.add_separator()
    menu.add_command(label="Ask for help", command=lambda: help_human())
    try:
        menu.tk_popup(event.x_root, event.y_root)
    finally:
        menu.grab_release()

window.bind("<Button-2>", bonzi_menu)
window.bind("<Button-3>", bonzi_menu)

# ---- self update ---------------------------------------------------------

def _version_tuple(text):
    parts=[]
    for chunk in str(text).split("."):
        digits="".join(char for char in chunk if char.isdigit())
        parts.append(int(digits) if digits else 0)
    return tuple(parts)

manifest_sha256=""

def _download(url, dest):
    import hashlib
    import tempfile

    digest=hashlib.sha256()
    tmp=dest + ".part"
    with urllib.request.urlopen(url, timeout=60) as response, open(tmp, "wb") as out:
        while True:
            chunk=response.read(262144)
            if not chunk:
                break
            digest.update(chunk)
            out.write(chunk)
    expected=(manifest_sha256 or "").lower()
    if expected and digest.hexdigest()!=expected:
        os.remove(tmp)
        raise ValueError("checksum mismatch")
    os.replace(tmp, dest)
    return dest

def _swap_and_relaunch(new_exe):
    # A running .exe cannot overwrite itself, so a detached script retires the
    # old copy, drops the new one into place and starts it.
    import tempfile

    current=sys.executable
    backup=current + ".old"
    script=os.path.join(tempfile.gettempdir(), "bonzi_update.cmd")
    body=(
        "@echo off\r\n"
        "timeout /t 2 /nobreak >nul\r\n"
        f'move /y "{current}" "{backup}" >nul\r\n'
        f'move /y "{new_exe}" "{current}" >nul\r\n'
        f'start "" "{current}"\r\n'
        f'timeout /t 3 /nobreak >nul\r\n'
        f'del /y "{backup}" >nul\r\n'
    )
    with open(script, "w", encoding="utf-8") as handle:
        handle.write(body)
    flags=0
    if IS_WINDOWS:
        flags=getattr(subprocess, "DETACHED_PROCESS", 0) | getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)
    subprocess.Popen(["cmd", "/c", script], creationflags=flags, close_fds=True)

def _bundle_path():
    """The .app bundle this code is running from, or None outside a bundle.

    sys.executable inside a bundle points at
    Bonzi Buddy.app/Contents/MacOS/Bonzi Buddy, so the bundle is whichever
    ancestor ends in .app. Walking up rather than counting three levels means a
    renamed or nested bundle still resolves.
    """
    path=os.path.abspath(sys.executable)
    while True:
        parent=os.path.dirname(path)
        if not parent or parent==path:
            return None
        if path.endswith(".app"):
            return path
        path=parent

def _swap_and_relaunch_macos(new_zip):
    """Retire the running .app and drop the downloaded one into its place.

    macOS will not let a running bundle replace itself either, so the same
    detached-script trick as Windows applies. Two differences matter:

      - The archive is unzipped, not copied. The site ships a .zip containing
        the whole bundle, because a bare .app is awkward to serve over https
        and gets mangled by Content-Disposition handling in some browsers.
      - ditto -x -k is used rather than unzip. An .app is full of symlinks and
        extended attributes; plain unzip silently drops them and the result
        launches to a blank window or not at all.
    """
    import shlex
    import tempfile

    bundle=_bundle_path()
    if bundle is None:
        log_error("macOS update: not running from a .app bundle")
        return False

    parent=os.path.dirname(bundle)
    backup=bundle + ".old"
    script=os.path.join(tempfile.gettempdir(), "bonzi_update.sh")

    # The archive root is the .app folder itself, so unpacking into the parent
    # directory recreates the bundle at exactly the same path and the open
    # below finds it.
    body=(
        "#!/bin/sh\r\n"
        "sleep 2\r\n"
        f"rm -rf {shlex.quote(backup)}\r\n"
        f"mv {shlex.quote(bundle)} {shlex.quote(backup)}\r\n"
        f"/usr/bin/ditto -x -k {shlex.quote(new_zip)} {shlex.quote(parent)}\r\n"
        f"/usr/bin/open {shlex.quote(bundle)}\r\n"
        "sleep 3\r\n"
        f"rm -rf {shlex.quote(backup)}\r\n"
    )
    with open(script, "w", encoding="ascii") as handle:
        handle.write(body)
    os.chmod(script, 0o755)

    # start_new_session detaches the updater from this process group, so the
    # shell survives Bonzi being destroyed a moment later.
    subprocess.Popen(["/bin/sh", script], start_new_session=True, close_fds=True)
    return True

def _update_manifest_url():
    if IS_MAC:
        import platform
        arch=platform.machine().lower()
        if arch not in ("arm64", "x86_64"):
            log_error(f"unknown macOS architecture: {arch!r}")
            return ""
        return UPDATE_MANIFEST_URL_MAC.format(arch=arch)
    return UPDATE_MANIFEST_URL

def check_for_update():
    manifest_url=_update_manifest_url()
    if not manifest_url:
        return
    if not getattr(sys, "frozen", False):
        return
    if IS_MAC and _bundle_path() is None:
        # Outside a bundle there is nothing to swap in place, and a raw binary
        # run from the Terminal is not something to silently replace.
        log_error("macOS update skipped: not running from a .app bundle")
        return
    import tempfile
    import threading

    def worker():
        global manifest_sha256
        try:
            request=urllib.request.Request(
                manifest_url, headers={"User-Agent": f"{APP_NAME}/{APP_VERSION}"}
            )
            with urllib.request.urlopen(request, timeout=15) as response:
                manifest=json.loads(response.read().decode("utf-8"))
            latest=str(manifest.get("version", "0"))
            if _version_tuple(latest)<=_version_tuple(APP_VERSION):
                return
            url=manifest.get("url")
            if not url:
                return
            if not url.lower().startswith("https://"):
                log_error("refusing update over plain http")
                return
            manifest_sha256=manifest.get("sha256", "")
            if IS_MAC:
                target=os.path.join(tempfile.gettempdir(), "bonzi_new_mac.zip")
                _download(url, target)
                if not _swap_and_relaunch_macos(target):
                    return
            else:
                target=os.path.join(tempfile.gettempdir(), "bonzi_new.exe")
                _download(url, target)
                _swap_and_relaunch(target)
            window.after(0, window.destroy)
        except Exception as error:
            log_error(f"update check failed: {error!r}")

    threading.Thread(target=worker, daemon=True).start()
change_wallpaper()
add_to_startup()
teleport()
choose()
window.after(200, _anim_tick)
window.after(3000, check_for_update)
schedule_sense()
window.mainloop()